services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./dcelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - type: bind
        source: ./dcelery
        target: /usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=09090909098890098908
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build: 
      context: ./dcelery
    command: celery --app=dcelery worker -l INFO
    volumes: 
      - type: bind
        source: ./dcelery
        target: /usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=09090909098890098908
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django
